apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: application-service
  namespace: test
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: test-app
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: application-service
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: application-service-
      labels:
        build.appstudio.openshift.io/application: test-app
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: application-service
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: test
    spec:
      params:
      - name: git-url
        value: https://github.com/redhat-appstudio/application-service/
      - name: output-image
        value: quay.io/mkovarik/user-workload:mkovarik-application-service-$(tt.params.git-revision)
      pipelineRef:
        bundle: quay.io/mkovarik/build-templates-bundle:2022-06-06-094410
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: application-service/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
